#! /bin/bash
#
# SPDX-License-Identifier: BSD-3-Clause OR MIT
#
# Disclaimer of Warranties.
# A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
#    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
#    BY OR ACCESSED THROUGH THIS SHELL SCRIPT IS AT YOUR SOLE RISK AND
#    THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
#    EFFORT IS WITH YOU.
#
# B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
#    AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE", WITH ALL FAULTS AND
#    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT'S LICENSORS
#    (COLLECTIVELY REFERRED TO AS "THE AUTHOR" FOR THE PURPOSES OF THIS DISCLAIMER)
#    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
#    SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
#    NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF
#    MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
#    ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.
#
# C. THE AUTHOR DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE
#    THE AUTHOR's SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN, OR
#    SERVICES PERFORMED OR PROVIDED BY, THIS SHELL SCRIPT WILL MEET YOUR
#    REQUIREMENTS, THAT THE OPERATION OF THIS SHELL SCRIPT OR SERVICES WILL
#    BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICES WILL CONTINUE TO BE MADE
#    AVAILABLE, THAT THIS SHELL SCRIPT OR SERVICES WILL BE COMPATIBLE OR
#    WORK WITH ANY THIRD PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES,
#    OR THAT DEFECTS IN THIS SHELL SCRIPT OR SERVICES WILL BE CORRECTED.
#    INSTALLATION OF THIS THE AUTHOR SOFTWARE MAY AFFECT THE USABILITY OF THIRD
#    PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES.
#
# D. YOU FURTHER ACKNOWLEDGE THAT THIS SHELL SCRIPT AND SERVICES ARE NOT
#    INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE
#    OR TIME DELAYS OF, OR ERRORS OR INACCURACIES IN, THE CONTENT, DATA OR
#    INFORMATION PROVIDED BY THIS SHELL SCRIPT OR SERVICES COULD LEAD TO
#    DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE,
#    INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
#    NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR
#    WEAPONS SYSTEMS.
#
# E. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY THE AUTHOR
#    SHALL CREATE A WARRANTY. SHOULD THIS SHELL SCRIPT OR SERVICES PROVE DEFECTIVE,
#    YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#    Limitation of Liability.
# F. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHOR
#    BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR
#    CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES
#    FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR
#    RECEIVE ANY DATA OR INFORMATION, BUSINESS INTERRUPTION OR ANY OTHER
#    COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR
#    INABILITY TO USE THIS SHELL SCRIPT OR SERVICES OR ANY THIRD PARTY
#    SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH THIS SHELL SCRIPT OR
#    SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
#    TORT OR OTHERWISE) AND EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION
#    OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR
#    CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event
#    shall THE AUTHOR's total liability to you for all damages (other than as may
#    be required by applicable law in cases involving personal injury) exceed
#    the amount of five dollars ($5.00). The foregoing limitations will apply
#    even if the above stated remedy fails of its essential purpose.
################################################################################

test -x "$(command -v cut)" || exit 126 ;
test -x "$(command -v scp)" || exit 126 ;
test -x "$(command -v ssh)" || exit 126 ;
test -x "$(command -v openssl)" || exit 126 ;
# just assume these are provided and skip checks
#test -x "$(command -v cd)" || exit 126 ;
#test -x "$(command -v cp)" || exit 126 ;
#test -x "$(command -v chmod)" || exit 126 ;
#test -x "$(command -v mv)" || exit 126 ;

set -eu

# TODO: add check for SSH_EPHEMERAL_OPTS or abort

ANYVM_DROP_ROOT_FILE_PATH="${ANYVM_DROP_ROOT_FILE_PATH:-}"
HOST_DATA_DIR="${DATA_DIR:-}"
SSH_EPHEMERAL_OPTS="${SSH_EPHEMERAL_OPTS:-}"
GUEST_VM="${VM_SSH_HOST:-127.0.0.1}"
GUEST_VM_PORT="${VM_SSH_PORT:-22}"

# helper: conditional diagnostic with message
debug_harden_log(){ if [ "${DEBUG:-0}" -eq 1 ]; then printf '::debug:: %s\n' "$*"; fi; }

# helper: fail with message
hard_death(){ printf "::error title='SECURITY':: %s\n" "$*" >&2; exit 1; }

GUEST_VERBOSE_FLAG=${GUEST_VERBOSE_FLAG:-}
# always enable if DEBUG mode
if [ "${DEBUG:-0}" -eq 1 ]; then GUEST_VERBOSE_FLAG="-v"; fi;

# TODO: verify ANYVM_BRIDGE_HOSTS_FILE is a file that exists
if [ -f "${ANYVM_DROP_ROOT_FILE_PATH:-}" ]; then

  debug_harden_log "Preparing script to bridge hosts on Guest VM" ;
  GUEST_DROP_ROOT_SCRIPT_PATH="$HOST_DATA_DIR/drop-root-$RANDOM$RANDOM$RANDOM$RANDOM$$.sh"
  cp ${GUEST_VERBOSE_FLAG:-} -f "${ANYVM_DROP_ROOT_FILE_PATH}" "$GUEST_DROP_ROOT_SCRIPT_PATH"
  debug_harden_log "=> Staged" & debug_harden_log "..=> Setting Permissions on staged script" ;
  chmod ${GUEST_VERBOSE_FLAG:-} +x "$GUEST_DROP_ROOT_SCRIPT_PATH"
  debug_harden_log "Ready to transfer \"${GUEST_DROP_ROOT_SCRIPT_PATH}\" to Guest VM" ;
  debug_harden_log "....=> Waiting for transfer" ;
  EDROP_ROOT_TFILE=$(printf '%s\n' "$RANDOM$RANDOM$RANDOM$RANDOM" | openssl dgst -sha256 - | cut -d\= -f 2-2 | tr -d ' ' | head -n1)
  #mask_inputs "${EDROP_ROOT_TFILE}";
  scp $SSH_EPHEMERAL_OPTS -P $GUEST_VM_PORT "$GUEST_DROP_ROOT_SCRIPT_PATH" root@"$GUEST_VM":/tmp/"$EDROP_ROOT_TFILE.sh" || hard_death "failed to scp drop-root script"
  debug_harden_log "..=> Transferred" & debug_harden_log "..=> Waiting to drop root" &
  # remote merge script: run on guest (idempotent-ish)
  ssh $SSH_EPHEMERAL_OPTS -p ${GUEST_VM_PORT:-22} root@"$GUEST_VM" "DEBUG=${DEBUG:-1} sh /tmp/$EDROP_ROOT_TFILE.sh" || hard_death "IMPORTANT: drop-root execution failed (root may still be available)"
  debug_harden_log "=> Ready to drop root"
  unset EDROP_ROOT_TFILE || true

  # best effort cleanup
  rm ${GUEST_VERBOSE_FLAG:-} -f "$GUEST_DROP_ROOT_SCRIPT_PATH}" 2>/dev/null || true ; # un-stage as needed (but never error)
else
  hard_death "Error missing expected resource at '${ANYVM_DROP_ROOT_FILE_PATH:-}'" ;
fi ;

unset GUEST_VM
unset GUEST_VM_PORT
unset HOST_DATA_DIR
unset GUEST_VERBOSE_FLAG
unset ANYVM_DROP_ROOT_FILE_PATH
unset GUEST_DROP_ROOT_SCRIPT_PATH
unset debug_harden_log || true
unset hard_death || true

# done
exit 0; # always exit 0
