# .github/workflows/Labeler.yml
---
name: "Pull Request Labeler"
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: ["main", "master", "stable"]

# Declare default permissions as none.
permissions: {}
# Seealso declared per-job permissions:
# - read-only permissions for contents and action runs.
# - read-write permissions for PRs (e.g., to update PR labels).

jobs:
  triage:
    permissions:
      actions: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
      with:
        repo-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
        sync-labels: true  # also remove labels automatically
