# .github/workflows/Test-utils-guest-release-fetching.yml
---
name: Test latest-vm-release utility
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
    paths:
      - 'action.yml'
      - 'utils/latest-vm-release.sh'
      - '.github/workflows/Test-utils-guest-release-fetching.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}  # Setting default permissions to none for enhanced security

jobs:
  test-latest-vm-release-util:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            runner: macos-26-intel
          - architecture: arm64
            runner: macos-latest
          - architecture: amd64
            runner: ubuntu-latest
          - architecture: arm64
            runner: ubuntu-26.04-arm
          - architecture: amd64
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: false
          submodules: false
          repository: 'reactive-firewall/anyvm-in-ci'
          sparse-checkout: 'utils/latest-vm-release.sh'
      - id: exercise-latest-vm-release-util
        name: Test latest-vm-release on ${{ runner.os }}
        if: ${{ !cancelled() && (github.repository == 'reactive-firewall/anyvm-in-ci') }}
        shell: bash
        run: |
          # exercise latest-vm-release
          if [[ -f utils/latest-vm-release.sh ]] ; then
            printf "::debug::%s\n" "Found utils/latest-vm-release.sh" ;
            [[ -x utils/latest-vm-release.sh ]] || chmod +x utils/latest-vm-release.sh ;
            for SOME_T_OS in 'freebsd' 'ghostbsd' 'openbsd' 'netbsd' 'dragonflybsd' 'midnightbsd' 'solaris' 'omnios' 'openindiana' 'tribblix' 'haiku' 'ubuntu' 'blissos' ; do
              printf "::debug::%s\n" "Exercising utils/latest-vm-release.sh ${SOME_T_OS}" ;
              utils/latest-vm-release.sh "${SOME_T_OS:-}" || exit 1 ;
            done;
          else
            printf "::debug::%s\n" "Could not find a testable utils/latest-vm-release.sh" ;
            exit 126 ;
          fi;
          exit 0 ;
